# Generated by Django 5.1.4 on 2025-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0004_member_created_by_member_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='member_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_input', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'member_config',
            },
        ),
    ]
