# Generated by Django 5.1.4 on 2025-02-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0001_initial'),
        ('member_app', '0007_member_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='entity_app.entity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
