# Generated by Django 5.1.4 on 2025-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0008_member_entity_alter_member_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
