# Generated by Django 5.1.4 on 2025-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0009_alter_member_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tithe_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='tithe_pay_type',
            field=models.CharField(blank=True, choices=[('person', 'Person Pay'), ('group', 'Group Pay')], max_length=50, null=True),
        ),
    ]
