# Generated by Django 5.1.4 on 2025-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0010_member_tithe_pay_member_tithe_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address_1',
            field=models.CharField(default=1, max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='address_2',
            field=models.CharField(blank=True, max_length=510),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
