# Generated by Django 5.1.4 on 2025-02-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0011_member_address_1_member_address_2_member_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address_2',
        ),
    ]
