# Generated by Django 5.1.4 on 2025-02-13 11:49

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='transaction_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=20, unique=True),
        ),
    ]
