# Generated by Django 5.1.4 on 2025-02-26 11:10

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_app', '0005_delete_collection'),
        ('member_app', '0012_rename_address_1_member_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('tithes', 'Tithes'), ('mission', 'Mission'), ('partnership', 'Partnership'), ('offering', 'Offering')], max_length=50)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=250, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='member_app.member')),
            ],
            options={
                'db_table': 'collection_transaction',
            },
        ),
    ]
