# Generated by Django 5.1.4 on 2025-02-26 11:19

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_alter_collection_transaction_transaction_id'),
        ('member_app', '0012_rename_address_1_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_transaction',
            name='transaction_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=250, null=True)),
                ('first_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approver_1', to='member_app.member')),
                ('second_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approver_2', to='member_app.member')),
            ],
            options={
                'db_table': 'collection',
            },
        ),
    ]
