# Generated by Django 5.1.4 on 2025-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0009_alter_collection_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
