# Generated by Django 5.1.4 on 2025-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0010_alter_collection_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_transaction',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
