# Generated by Django 5.1.4 on 2025-03-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0012_alter_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_transaction',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ct_collection_id', to='collection_app.collection'),
        ),
    ]
