# Generated by Django 5.1.4 on 2025-03-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0003_entity_address_entity_city_entity_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='secondary_phone',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
